// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/properties": {
    params: {};
  };
  "/properties/:slug": {
    params: {
      "slug": string;
    };
  };
  "/p/:id": {
    params: {
      "id": string;
    };
  };
  "/share/:id": {
    params: {
      "id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/loan-services": {
    params: {};
  };
  "/post": {
    params: {};
  };
  "/favorites": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/b/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/profile-settings": {
    params: {};
  };
  "/sps-internal-admin/login": {
    params: {};
  };
  "/sps-internal-admin": {
    params: {};
  };
  "/sps-internal-admin/properties": {
    params: {};
  };
  "/sps-internal-admin/properties/new": {
    params: {};
  };
  "/sps-internal-admin/properties/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/sps-internal-admin/hero-slides": {
    params: {};
  };
  "/sps-internal-admin/homepage-sections": {
    params: {};
  };
  "/sps-internal-admin/popular-locations": {
    params: {};
  };
  "/sps-internal-admin/pending-properties": {
    params: {};
  };
  "/sps-internal-admin/users": {
    params: {};
  };
  "/sps-internal-admin/settings": {
    params: {};
  };
  "/sps-internal-admin/my-properties": {
    params: {};
  };
  "/sps-internal-admin/leads": {
    params: {};
  };
  "/sps-internal-admin/loan-requests": {
    params: {};
  };
  "/sps-internal-admin/activities": {
    params: {};
  };
  "/sps-internal-admin/blogs": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/properties" | "/properties/:slug" | "/p/:id" | "/share/:id" | "/contact" | "/loan-services" | "/post" | "/favorites" | "/blogs" | "/blogs/:slug" | "/b/:id" | "/login" | "/profile" | "/profile-settings" | "/sps-internal-admin/login" | "/sps-internal-admin" | "/sps-internal-admin/properties" | "/sps-internal-admin/properties/new" | "/sps-internal-admin/properties/edit/:id" | "/sps-internal-admin/hero-slides" | "/sps-internal-admin/homepage-sections" | "/sps-internal-admin/popular-locations" | "/sps-internal-admin/pending-properties" | "/sps-internal-admin/users" | "/sps-internal-admin/settings" | "/sps-internal-admin/my-properties" | "/sps-internal-admin/leads" | "/sps-internal-admin/loan-requests" | "/sps-internal-admin/activities" | "/sps-internal-admin/blogs";
  };
  "routes/_public.jsx": {
    id: "routes/_public";
    page: "/" | "/properties" | "/properties/:slug" | "/p/:id" | "/share/:id" | "/contact" | "/loan-services" | "/post" | "/favorites" | "/blogs" | "/blogs/:slug" | "/b/:id" | "/login" | "/profile" | "/profile-settings";
  };
  "routes/_public.home.jsx": {
    id: "routes/_public.home";
    page: "/";
  };
  "routes/_public.properties.jsx": {
    id: "routes/_public.properties";
    page: "/properties";
  };
  "routes/_public.properties.$slug.jsx": {
    id: "routes/_public.properties.$slug";
    page: "/properties/:slug";
  };
  "routes/_public.p.$id.jsx": {
    id: "routes/_public.p.$id";
    page: "/p/:id";
  };
  "routes/_public.share.$id.jsx": {
    id: "routes/_public.share.$id";
    page: "/share/:id";
  };
  "routes/_public.contact.jsx": {
    id: "routes/_public.contact";
    page: "/contact";
  };
  "routes/_public.loan-services.jsx": {
    id: "routes/_public.loan-services";
    page: "/loan-services";
  };
  "routes/_public.post.jsx": {
    id: "routes/_public.post";
    page: "/post";
  };
  "routes/_public.favorites.jsx": {
    id: "routes/_public.favorites";
    page: "/favorites";
  };
  "routes/_public.blogs.jsx": {
    id: "routes/_public.blogs";
    page: "/blogs";
  };
  "routes/_public.blogs.$slug.jsx": {
    id: "routes/_public.blogs.$slug";
    page: "/blogs/:slug";
  };
  "routes/_public.b.$id.jsx": {
    id: "routes/_public.b.$id";
    page: "/b/:id";
  };
  "routes/_public.login.jsx": {
    id: "routes/_public.login";
    page: "/login";
  };
  "routes/_public.profile.jsx": {
    id: "routes/_public.profile";
    page: "/profile";
  };
  "routes/_public.profile-settings.jsx": {
    id: "routes/_public.profile-settings";
    page: "/profile-settings";
  };
  "routes/_admin.login.jsx": {
    id: "routes/_admin.login";
    page: "/sps-internal-admin/login";
  };
  "routes/_admin.jsx": {
    id: "routes/_admin";
    page: "/sps-internal-admin" | "/sps-internal-admin/properties" | "/sps-internal-admin/properties/new" | "/sps-internal-admin/properties/edit/:id" | "/sps-internal-admin/hero-slides" | "/sps-internal-admin/homepage-sections" | "/sps-internal-admin/popular-locations" | "/sps-internal-admin/pending-properties" | "/sps-internal-admin/users" | "/sps-internal-admin/settings" | "/sps-internal-admin/my-properties" | "/sps-internal-admin/leads" | "/sps-internal-admin/loan-requests" | "/sps-internal-admin/activities" | "/sps-internal-admin/blogs";
  };
  "routes/_admin.dashboard.jsx": {
    id: "routes/_admin.dashboard";
    page: "/sps-internal-admin";
  };
  "routes/_admin.properties.jsx": {
    id: "routes/_admin.properties";
    page: "/sps-internal-admin/properties";
  };
  "routes/_admin.properties.new.jsx": {
    id: "routes/_admin.properties.new";
    page: "/sps-internal-admin/properties/new";
  };
  "routes/_admin.properties.edit.$id.jsx": {
    id: "routes/_admin.properties.edit.$id";
    page: "/sps-internal-admin/properties/edit/:id";
  };
  "routes/_admin.hero-slides.jsx": {
    id: "routes/_admin.hero-slides";
    page: "/sps-internal-admin/hero-slides";
  };
  "routes/_admin.homepage-sections.jsx": {
    id: "routes/_admin.homepage-sections";
    page: "/sps-internal-admin/homepage-sections";
  };
  "routes/_admin.popular-locations.jsx": {
    id: "routes/_admin.popular-locations";
    page: "/sps-internal-admin/popular-locations";
  };
  "routes/_admin.pending-properties.jsx": {
    id: "routes/_admin.pending-properties";
    page: "/sps-internal-admin/pending-properties";
  };
  "routes/_admin.users.jsx": {
    id: "routes/_admin.users";
    page: "/sps-internal-admin/users";
  };
  "routes/_admin.settings.jsx": {
    id: "routes/_admin.settings";
    page: "/sps-internal-admin/settings";
  };
  "routes/_admin.my-properties.jsx": {
    id: "routes/_admin.my-properties";
    page: "/sps-internal-admin/my-properties";
  };
  "routes/_admin.leads.jsx": {
    id: "routes/_admin.leads";
    page: "/sps-internal-admin/leads";
  };
  "routes/_admin.loan-requests.jsx": {
    id: "routes/_admin.loan-requests";
    page: "/sps-internal-admin/loan-requests";
  };
  "routes/_admin.activities.jsx": {
    id: "routes/_admin.activities";
    page: "/sps-internal-admin/activities";
  };
  "routes/_admin.blogs.jsx": {
    id: "routes/_admin.blogs";
    page: "/sps-internal-admin/blogs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_public": typeof import("./app/routes/_public.jsx");
  "routes/_public.home": typeof import("./app/routes/_public.home.jsx");
  "routes/_public.properties": typeof import("./app/routes/_public.properties.jsx");
  "routes/_public.properties.$slug": typeof import("./app/routes/_public.properties.$slug.jsx");
  "routes/_public.p.$id": typeof import("./app/routes/_public.p.$id.jsx");
  "routes/_public.share.$id": typeof import("./app/routes/_public.share.$id.jsx");
  "routes/_public.contact": typeof import("./app/routes/_public.contact.jsx");
  "routes/_public.loan-services": typeof import("./app/routes/_public.loan-services.jsx");
  "routes/_public.post": typeof import("./app/routes/_public.post.jsx");
  "routes/_public.favorites": typeof import("./app/routes/_public.favorites.jsx");
  "routes/_public.blogs": typeof import("./app/routes/_public.blogs.jsx");
  "routes/_public.blogs.$slug": typeof import("./app/routes/_public.blogs.$slug.jsx");
  "routes/_public.b.$id": typeof import("./app/routes/_public.b.$id.jsx");
  "routes/_public.login": typeof import("./app/routes/_public.login.jsx");
  "routes/_public.profile": typeof import("./app/routes/_public.profile.jsx");
  "routes/_public.profile-settings": typeof import("./app/routes/_public.profile-settings.jsx");
  "routes/_admin.login": typeof import("./app/routes/_admin.login.jsx");
  "routes/_admin": typeof import("./app/routes/_admin.jsx");
  "routes/_admin.dashboard": typeof import("./app/routes/_admin.dashboard.jsx");
  "routes/_admin.properties": typeof import("./app/routes/_admin.properties.jsx");
  "routes/_admin.properties.new": typeof import("./app/routes/_admin.properties.new.jsx");
  "routes/_admin.properties.edit.$id": typeof import("./app/routes/_admin.properties.edit.$id.jsx");
  "routes/_admin.hero-slides": typeof import("./app/routes/_admin.hero-slides.jsx");
  "routes/_admin.homepage-sections": typeof import("./app/routes/_admin.homepage-sections.jsx");
  "routes/_admin.popular-locations": typeof import("./app/routes/_admin.popular-locations.jsx");
  "routes/_admin.pending-properties": typeof import("./app/routes/_admin.pending-properties.jsx");
  "routes/_admin.users": typeof import("./app/routes/_admin.users.jsx");
  "routes/_admin.settings": typeof import("./app/routes/_admin.settings.jsx");
  "routes/_admin.my-properties": typeof import("./app/routes/_admin.my-properties.jsx");
  "routes/_admin.leads": typeof import("./app/routes/_admin.leads.jsx");
  "routes/_admin.loan-requests": typeof import("./app/routes/_admin.loan-requests.jsx");
  "routes/_admin.activities": typeof import("./app/routes/_admin.activities.jsx");
  "routes/_admin.blogs": typeof import("./app/routes/_admin.blogs.jsx");
};